### ISSUE TITLE
SGD is not generating the Package.xml

### ISSUE THREAD

**Issue by bhoaraju** [scolladon/sfdx-git-delta#997]
## What is the problem?
we are currently experiencing issues with generating the package.xml file using SFDX-Git-Delta

## Steps to reproduce

1. Install the SFDX-Git-Delta and it should generate the package as soon as we run the below command:
2. sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir "." 

## Execution context

---

**Operating System:** …
Windows
**npm version:** …
10.9.2
**node version:** …
v22.13.0
**sf version:** …
@salesforce/cli/2.73.9 win32-x64 node-v22.12.0
**sgd plugin version:** …
latest

**Comment by bhoaraju** [comment]
**What is the parameter and the value you used with it?**
sf plugins install "sfdx-git-delta@latest,
sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir "." 

**What is the expected result?**

C:\ProgramData\Jenkins\.jenkins\workspace\Salesforce Validation SC_DVT>sf sgd:source:delta --to=HEAD --from=1166aa4711b066c1eec03d1f030c8921a8eb7d22 --output . 
 Â»   Warning: @salesforce/cli update available from [92m2.62.6[39m to [92m2.68.6[39m.
(node:1324) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "[INFORMATION] sfdx-git-delta v6 is coming soon! Read more and plan your migration: https://github.com/scolladon/sfdx-git-delta/issues/936"
  ]
}

**What is the actual result?**
C:\ProgramData\Jenkins\.jenkins\workspace\Salesforce Validation SC_DVT>sf sgd:source:delta --to=HEAD --from=${previousCommitId} --api-version=60.0 --output-dir . 
 Â»   Warning: @salesforce/cli update available from [92m2.72.21[39m to [92m2.73.9[39m.
    SyntaxError: Named export 'castArray' not found. The requested module 
    'lodash-es' is a CommonJS module, which may not support all module.exports
     as named exports.
    CommonJS modules can always be imported via the default export, for 
    example using:

    import pkg from 'lodash-es';
    const { castArray } = pkg;

**Comment by scolladon** [comment]
Hi @bhoaraju !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll try to propose a fix soon and will notify you in the PR so you can help with QA on windows

**Comment by scolladon** [comment]
The error message is very weird...

> 'lodash-es' is a CommonJS module...

It is not ! It is an ES Module...
If it was a CommonJS module it would not pass compilation...
And trying locally to apply the suggestion result in a compilation failure : "sfdx-git-delta/node_modules/@types/lodash-es/index"' has no default export."

**Comment by scolladon** [comment]
Could you try updating `sf-cli` and retry please ?

**Comment by scolladon** [comment]
> Do i need to update sf-cli in this location E:\apps\sf\bin or here C:\Windows\system32\config\systemprofile\AppData\Local\sf\node_modules.sfdx-git-delta\node_modules

You should not change anything in the node_modules, it should be resolved by npm alone

Can you try a uninstall and reinstall of sf cli and sfdx-git-delta plugin please ?

**Comment by scolladon** [comment]
Hi @bhoaraju 

How is going your installation?
Did it changed something?

**Comment by bhoaraju** [comment]
No @scolladon, i am still facing the same issue even after uninstall and reinstalling Sf cli and sfdx-git-delta.

**Comment by bhoaraju** [comment]
@scolladon yes i have installed latest version

**Comment by scolladon** [comment]
Could you show the result of sf plugins command please ?

**Comment by bhoaraju** [comment]
@scolladon - Getting this error when i am installing SGD in Jenkins but it is installed successfully in the server. Could you please set up sometime with me to connect and resolve the issue.

_C:\ProgramData\Jenkins\.jenkins\workspace\Salesforce Validation Job SCDVT delta trail>echo y   | sf plugins install "sfdx-git-delta@latest" 
 Â»   Warning: @salesforce/cli update available from [92m2.72.21[39m to [92m2.74.6[39m.
[32m?[39m [1msfdx-git-delta isn't signed by Salesforce. Only install the plugin if you [22m
[1mtrust its creator. Do you want to continue the installation?[22m [2m(y/N)[22m[1A[144G[145G[1B[2K[1A[2K[G[32m?[39m [1msfdx-git-delta isn't signed by Salesforce. Only install the plugin if you [22m
[1mtrust its creator. Do you want to continue the installation?[22m [2m(y/N)[22m y[1A[145G[146G[1B[2K[1A[2K[G[32m?[39m [1msfdx-git-delta isn't signed by Salesforce. Only install the plugin if you [22m
[1mtrust its creator. Do you want to continue the installation?[22m [2m(y/N)[22m y[1A[146G[144G[1B[2K[1A[2K[G[32m?[39m [1msfdx-git-delta isn't signed by Salesforce. Only install the plugin if you [22m
[1mtrust its creator. Do you want to continue the installation?[22m [36myes[39m[1A[141G[1B
[?25hBecause you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
Finished digital signature check.
@salesforce/cli: Installing plugin [36msfdx-git-delta@latest[39m... [1m[31mfailed[39m[22m
npm error code ERR_INVALID_ARG_TYPE
npm error The "from" argument must be of type string. Received undefined
npm error A complete log of this run can be found in: C:\Windows\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2025-02-04T08_20_33_698Z-debug-0.log
 Â»   Error: node "C:\Windows\System32\config\systemprofile\AppData\Local\sf\cli
 Â»   ent\2.72.21-6a74781\node_modules\npm\bin\npm-cli.js" install 
 Â»   sfdx-git-delta@latest --omit dev --no-audit --loglevel=notice --no-fund 
 Â»   exited with code 1
 Â»   Try this: Run with DEBUG=@oclif/plugin-plugins* to see debug output._

**Comment by bhoaraju** [comment]
@scolladon  Does 2PM IST works for you?

**Comment by scolladon** [comment]
It does !

**Comment by bhoaraju** [comment]
Hi @scolladon, i have scheduled a call(Google meet) at 2pm IST. Hope you have received it.
